version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: artestofados
      POSTGRES_USER: art
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-troque-esta-senha}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://art:${POSTGRES_PASSWORD:-troque-esta-senha}@db:5432/artestofados
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CALENDAR_ID_ONLINE: ${GOOGLE_CALENDAR_ID_ONLINE:-primary}
      GOOGLE_CALENDAR_ID_LOJA: ${GOOGLE_CALENDAR_ID_LOJA:-primary}
      # adicione aqui outras variáveis necessárias
    depends_on:
      - db
    expose:
      - "3000"
    restart: unless-stopped

  web:
    build:
      context: ./desktop
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
      - web
    restart: unless-stopped

volumes:
  db_data:
  caddy_data:
  caddy_config:
